
library(R.matlab)
library(caret)
library(boot)
library(e1071)
library(nnet)

proj_dir = 'C:\\Users\\Andrew\\Documents\\Stanford\\cs221\\221project\\'

labels = read.csv(paste0(proj_dir, "data\\train_info.csv")) # stringsAsFactors = F

features = data.frame(readMat(paste0(proj_dir, "featureMat.mat")))

# Load features and labels generated by Matlab from dataset
# y = data.frame(readMat("/Users/daniel/Dropbox/Stanford/2015-2016/Fall 2015/CS 229/Project/Data/features/labels3.mat"))
# X = data.frame(readMat("/Users/daniel/Dropbox/Stanford/2015-2016/Fall 2015/CS 229/Project/Data/features/features3.mat"))

# Set RNG seed for determining cross-validation folds
set.seed(1024)

# get a random sample of test pictures
numPictures = dim(features)[1]



rm(newLabels)
for (i in seq(1,numPictures)) {
  ind = which(labels[,1]==paste0(features[i,1], ".jpg"))
  
  if (!exists("newLabels")) {
    newLabels = labels[ind,]
  }
  else {
    newLabels = rbind(newLabels, labels[ind,])
  }
}

numFeatures = dim(features)[2]

picsToCompare = 20
rands = sample(seq(1,dim(newLabels)[1]), picsToCompare, replace=F)


rm(pairFeatures)
rm(pairLabels)
for (i in 1:picsToCompare) {
  
  firstPicFeatures = features[rands[i], 2:numFeatures]
  for (j in 1:numPictures){
    secondPicFeatures = features[j, 2:numFeatures]
    
    newFeatRow = data.frame(firstPicFeatures, 
                            abs(secondPicFeatures-firstPicFeatures),
                            check.names = T)
    
    if (!exists("pairFeatures")) {
      pairFeatures = newFeatRow
    }
    else {
      pairFeatures = rbind(pairFeatures, newFeatRow)
    }
    
    pairLabRow = cbind(labels[rands[i],1], labels[j,1], 
                       labels[rands[i],]$artist == labels[j,]$artist,
                       labels[rands[i],]$style == labels[j,]$style,
                       labels[rands[i],]$genre == labels[j,]$genre
                       )
    
    if (!exists("pairLabels")) {
      pairLabels = pairLabRow
    }
    else {
      pairLabels = rbind(pairLabels, pairLabRow)
    }
  }
}

pairLabels = data.frame(pairLabels)
colnames(pairLabels) = c("pic1", "pic2", "sameArtist", "sameStyle", "sameGenre")


numHidden = 40
misclass = mat.or.vec(1,numHidden);
trainPredMat = mat.or.vec(numHidden, dim(pairFeatures)[1]);
# testPredMat = mat.or.vec(10, 1534);

featuresWithArtist = cbind(pairFeatures, sameArtist = pairLabels$sameArtist) #rep(c(1,0), 1550))#

# iterate over different numbers of nodes in hidden layer
# for (sz in seq(1, numHidden)) {
sz = 40
  
  # average over 10 observations for better results
  tsumPred = 0;
  # sumPred = 0;
  for (i in seq(1,10)) {
    set.seed(345 + i)
    artnet <- nnet(sameArtist~., data = featuresWithArtist,  
                   size = sz, rang = 0.5, decay = 0.1, 
                   MaxNWts = Inf, maxit = 2000);
    
    # predict on both the training and test set
    tpred <- predict(artnet, featuresWithArtist, type = "raw");
    tsumPred = tsumPred + tpred;
    #     pred <- predict(spamnet, spam.test, type = "raw")
    #     sumPred = sumPred + pred;
  }
  
  # calculate misclassification rates
  # avgPred = sumPred/10;
  tavgPred = tsumPred/10;
  trainPredMat[sz,] = tavgPred;
  # testPredMat[sz,] = avgPred;
  
  trueCol = dim(featuresWithArtist)[2]
  finalPred = round(tavgPred);
  correct = (finalPred == featuresWithArtist[,trueCol]);
  misclassification_rate = 1-sum(correct)/length(correct)
  falseNeg <- (finalPred == 0 & featuresWithArtist[,trueCol] == 1)
  falsePos <- (finalPred == 1 & featuresWithArtist[,trueCol] == 0)
  #   spam_misclassification_rate = sum(spam_incorrect)/sum(spam_tot);
  #   nspam_misclassification_rate = sum(nspam_incorrect)/sum(nspam_tot);
  
  misclass[sz] = misclassification_rate;
# }

trainPredMatArtist = trainPredMat
# trainPredMatArtistBack = trainPredMatArtist


featuresWithStyle = cbind(pairFeatures, sameStyle = pairLabels$sameStyle) #rep(c(1,0), 1550))#

# iterate over different numbers of nodes in hidden layer
for (sz in seq(1, numHidden)) {
  
  # average over 10 observations for better results
  tsumPred = 0;
  # sumPred = 0;
  for (i in seq(1,10)) {
    set.seed(345 + i)
    artnet <- nnet(sameStyle~., data = featuresWithStyle,  
                   size = sz, rang = 0.5, decay = 0.1, 
                   MaxNWts = Inf, maxit = 2000);
    
    # predict on both the training and test set
    tpred <- predict(artnet, featuresWithStyle, type = "raw");
    tsumPred = tsumPred + tpred;
    #     pred <- predict(spamnet, spam.test, type = "raw")
    #     sumPred = sumPred + pred;
  }
  
  # calculate misclassification rates
  # avgPred = sumPred/10;
  tavgPred = tsumPred/10;
  trainPredMat[sz,] = tavgPred;
  # testPredMat[sz,] = avgPred;
  
  trueCol = dim(featuresWithStyle)[2]
  finalPred = round(tavgPred);
  correct = (finalPred == featuresWithStyle[,trueCol]);
  misclassification_rate = 1-sum(correct)/length(correct)
  falseNeg <- (finalPred == 0 & featuresWithStyle[,trueCol] == 1)
  falsePos <- (finalPred == 1 & featuresWithStyle[,trueCol] == 0)
  #   spam_misclassification_rate = sum(spam_incorrect)/sum(spam_tot);
  #   nspam_misclassification_rate = sum(nspam_incorrect)/sum(nspam_tot);
  
  misclass[sz] = misclassification_rate;
}

trainPredMatStyle = trainPredMat
# trainPredMatStyleBack = trainPredMatStyle


featuresWithGenre = cbind(pairFeatures, sameGenre = pairLabels$sameGenre) #rep(c(1,0), 1550))#

# iterate over different numbers of nodes in hidden layer
for (sz in seq(1, numHidden)) {
  
  # average over 10 observations for better results
  tsumPred = 0;
  # sumPred = 0;
  for (i in seq(1,10)) {
    set.seed(345 + i)
    artnet <- nnet(sameGenre~., data = featuresWithGenre,  
                   size = sz, rang = 0.5, decay = 0.1, 
                   MaxNWts = Inf, maxit = 2000);
    
    # predict on both the training and test set
    tpred <- predict(artnet, featuresWithGenre, type = "raw");
    tsumPred = tsumPred + tpred;
    #     pred <- predict(spamnet, spam.test, type = "raw")
    #     sumPred = sumPred + pred;
  }
  
  # calculate misclassification rates
  # avgPred = sumPred/10;
  tavgPred = tsumPred/10;
  trainPredMat[sz,] = tavgPred;
  # testPredMat[sz,] = avgPred;
  
  trueCol = dim(featuresWithGenre)[2]
  finalPred = round(tavgPred);
  correct = (finalPred == featuresWithGenre[,trueCol]);
  misclassification_rate = 1-sum(correct)/length(correct)
  falseNeg <- (finalPred == 0 & featuresWithGenre[,trueCol] == 1)
  falsePos <- (finalPred == 1 & featuresWithGenre[,trueCol] == 0)
  #   spam_misclassification_rate = sum(spam_incorrect)/sum(spam_tot);
  #   nspam_misclassification_rate = sum(nspam_incorrect)/sum(nspam_tot);
  
  misclass[sz] = misclassification_rate;
}

trainPredMatGenre = trainPredMat
# trainPredMatGenreBack = trainPredMatGenre


## CACLULATE ALL THE THINGS ----------

sz = 40
avgYes = mean(trainPredMatArtist[sz, pairLabels$sameArtist==1])
avgNo = mean(trainPredMatArtist[sz, pairLabels$sameArtist==0])
threshold = (avgYes+avgNo)/2

C = 200


max.pred = max(trainPredMatArtist)
min.pred = min(trainPredMatArtist)
diff.pred = max.pred - min.pred
confidence = seq(from=min.pred - (diff.pred/C), to=max.pred, by=diff.pred/(C+1))


# Average sensitivity/specificity across all CV folds
avg.sensitivities = matrix(0,  C)
avg.specificities = matrix(0,  C)

# Sensitivity/specificity for each fold, for the current alarm
cv.sensitivities = array(0, C)
cv.specificities = array(0, C)

# for (k in 1:K) {
  for (c in 1:C) {
    
    
    y.pred.factor2 = factor(trainPredMatArtist[sz, ] >= confidence[c])
    
    levels(y.pred.factor2)[levels(y.pred.factor2) == FALSE] = 0
    levels(y.pred.factor2)[levels(y.pred.factor2) == TRUE] = 1
    
    # Convert labels and predictions to factors for the confusion matrix
    y.test.factor = factor(featuresWithArtist$sameArtist, levels=c(0,1))
    
    # Generate the confusion matrix and extract sensitivity/specificity
    CM = confusionMatrix(y.pred.factor2, y.test.factor)
    avg.sensitivities[c] = CM$byClass["Sensitivity"]
    avg.specificities[c] = CM$byClass["Specificity"]
  }
# }

plot(avg.sensitivities, avg.specificities, main = "Sens/Spec curve for Neural Net 40")

P = sum(pairLabels$sameArtist==1)
N = sum(pairLabels$sameArtist==0)
TP = sum(trainPredMatArtist[sz, pairLabels$sameArtist==1] > threshold)
FP = sum(trainPredMatArtist[sz, pairLabels$sameArtist==0] > threshold)
TN = sum(trainPredMatArtist[sz, pairLabels$sameArtist==0] < threshold)
FN = sum(trainPredMatArtist[sz, pairLabels$sameArtist==1] < threshold)

TPRa = (TP)/P
TNRa = TN/N
PPVa = TP/(TP+FP)

## FOR STYLE
avgYes = mean(trainPredMatStyle[10, pairLabels$sameStyle==1])
avgNo = mean(trainPredMatStyle[10, pairLabels$sameStyle==0])
threshold = (avgYes+avgNo)/2

P = sum(pairLabels$sameStyle==1)
N = sum(pairLabels$sameStyle==0)
TP = sum(trainPredMatStyle[10, pairLabels$sameStyle==1] > threshold)
FP = sum(trainPredMatStyle[10, pairLabels$sameStyle==0] > threshold)
TN = sum(trainPredMatStyle[10, pairLabels$sameStyle==0] < threshold)
FN = sum(trainPredMatStyle[10, pairLabels$sameStyle==1] < threshold)

TPRs = (TP)/P
TNRs = TN/N
PPVs = TP/(TP+FP)

## FOR GENRE
avgYes = mean(trainPredMatGenre[10, pairLabels$sameGenre==1])
avgNo = mean(trainPredMatGenre[10, pairLabels$sameGenre==0])
threshold = (avgYes+avgNo)/2

P = sum(pairLabels$sameGenre==1)
N = sum(pairLabels$sameGenre==0)
TP = sum(trainPredMatGenre[10, pairLabels$sameGenre==1] > threshold)
FP = sum(trainPredMatGenre[10, pairLabels$sameGenre==0] > threshold)
TN = sum(trainPredMatGenre[10, pairLabels$sameGenre==0] < threshold)
FN = sum(trainPredMatGenre[10, pairLabels$sameGenre==1] < threshold)

TPRg = (TP)/P
TNRg = TN/N
PPVg = TP/(TP+FP)



