# CS221 project

# random forest model
library(R.matlab)
library(caret)
library(boot)
library(e1071)
library(randomForest)

proj_dir = 'C:\\Users\\Andrew\\Documents\\Stanford\\cs221\\221project\\'

labels = read.csv(paste0(proj_dir, "data\\train_info.csv")) # stringsAsFactors = F


features = data.frame(readMat(paste0(proj_dir, "featureMat.mat")))

# Load features and labels generated by Matlab from dataset
# y = data.frame(readMat("/Users/daniel/Dropbox/Stanford/2015-2016/Fall 2015/CS 229/Project/Data/features/labels3.mat"))
# X = data.frame(readMat("/Users/daniel/Dropbox/Stanford/2015-2016/Fall 2015/CS 229/Project/Data/features/features3.mat"))


# Set RNG seed for determining cross-validation folds
set.seed(1024)


rm(newLabels)
for (i in seq(1,numPictures)) {
  ind = which(labels[,1]==paste0(features[i,1], ".jpg"))
  
  if (!exists("newLabels")) {
    newLabels = labels[ind,]
  }
  else {
    newLabels = rbind(newLabels, labels[ind,])
  }
}

numFeatures = dim(features)[2]

picsToCompare = 20
rands = sample(seq(1,dim(newLabels)[1]), picsToCompare, replace=F)


rm(pairFeatures)
rm(pairLabels)
for (i in 1:picsToCompare) {
  
  firstPicFeatures = features[rands[i], 2:numFeatures]
  for (j in 1:numPictures){
    secondPicFeatures = features[j, 2:numFeatures]
    
    newFeatRow = data.frame(firstPicFeatures, 
                            abs(secondPicFeatures-firstPicFeatures),
                            check.names = T)
    
    if (!exists("pairFeatures")) {
      pairFeatures = newFeatRow
    }
    else {
      pairFeatures = rbind(pairFeatures, newFeatRow)
    }
    
    pairLabRow = cbind(labels[rands[i],1], labels[j,1], 
                       labels[rands[i],]$artist == labels[j,]$artist,
                       labels[rands[i],]$style == labels[j,]$style,
                       labels[rands[i],]$genre == labels[j,]$genre
    )
    
    if (!exists("pairLabels")) {
      pairLabels = pairLabRow
    }
    else {
      pairLabels = rbind(pairLabels, pairLabRow)
    }
  }
}

pairLabels = data.frame(pairLabels)
colnames(pairLabels) = c("pic1", "pic2", "sameArtist", "sameStyle", "sameGenre")



# Set number of features to select per tree split (mtry)
p = dim(features)[2]
mp = ceiling(p/3)
#mp = ceiling(sqrt(p))



featuresWithArtist = cbind(pairFeatures, sameArtist = pairLabels$sameArtist) #rep(c(1,0), 1550))#

# iterate over different numbers of nodes in hidden layer
lastInd = dim(featuresWithArtist)[2]

K = 5 # number of CV folds
folds = createFolds(pairLabels$sameArtist, k=K, list=TRUE, returnTrain=FALSE)

# Sensitivity/specificity for each fold, for the current alarm

confidence = seq(from=0, to=.5, by=0.01)
C = length(confidence)

# Average sensitivity/specificity across all CV folds
avg.sensitivities = matrix(0,  C)
avg.specificities = matrix(0,  C)

# Sensitivity/specificity for each fold, for the current alarm
cv.sensitivities = array(0, c( C, K))
cv.specificities = array(0, c( C, K))


# Train/test per fold
for (k in 1:K) {
  
  # Format the current fold indices and separate out the test/train sets
  fold = unlist(folds[k])
  X.train = pairFeatures[-fold,]
  X.test = pairFeatures[fold,]
  y.train = factor(pairLabels$sameArtist[-fold])
  y.test = factor(pairLabels$sameArtist[fold])
  
  # Build the svm regression model using the current training set.
  rf.fit = randomForest(x = X.train, y = y.train, ntree = 501, importance = TRUE,
                        xtest = X.test, ytest = y.test, mtry=mp)
  
  
  for (c in 1:C) {
    # Generate the predictions using the current fold as a validation set.
    # y.pred.factor = predict(rf.fit, X.test, type = "response")
    # y.pred.factor = rf.fit$test$predicted
    y.pred.factor = as.factor(rf.fit$test$votes[,2] >= confidence[c])
    levels(y.pred.factor)[levels(y.pred.factor) == FALSE] = 0
    levels(y.pred.factor)[levels(y.pred.factor) == TRUE] = 1
    
    # Convert labels and predictions to factors for the confusion matrix
    y.test.factor = factor(y.test, levels=c(0,1))
    
    # Generate the confusion matrix and extract sensitivity/specificity
    CM = confusionMatrix(y.pred.factor, y.test.factor)
    cv.sensitivities[ c, k] = CM$byClass["Sensitivity"]
    cv.specificities[ c, k] = CM$byClass["Specificity"]
  }
}

# Average the current alarm's specificity/sensitivity over all CV estimates
for (c in 1:C) {
  avg.sensitivities[ c] = mean(cv.sensitivities[ c,])
  avg.specificities[ c] = mean(cv.specificities[ c,])
}

randomforest_ss = data.frame(sens = avg.sensitivities, spec =  avg.specificities)

plot(avg.sensitivities, avg.specificities, main = "Sens/Spec curve for Random Forest")
